ARG NODE_VERSION="15.3.0"
FROM node:${NODE_VERSION}-alpine AS frontend-builder

COPY frontend/ /app/
WORKDIR /app

RUN apk add -U --no-cache git python3 make g++ \
    # && npm install -g yarn \
    && yarn install \
    && yarn build \
    && apk del --no-cache git make g++

FROM nginx:1.17.4-alpine AS runtime

COPY --from=frontend-builder /app/dist /var/www/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
